modLoader="javafml" 
loaderVersion="[28,)" 
issueTrackerURL="http://my.issue.tracker/"
[[mods]] 
modId="itemdespawnlooker" 
version="1.0.0" 
displayName="Item Despawn Looker"
updateJSONURL="http://myurl.me/" 
displayURL="" 
logoFile="" 
credits="" 
authors="MORIMORI0317" 
description='''
Thank you for downloading!!
'''
